"""Encryption in transit: source site -> cloud-hosted enclave.

Hybrid encryption, the same pattern real TLS/attested-enclave session-key
provisioning uses: a fresh AES-256-GCM key encrypts the payload, and that
key is itself wrapped with the recipient's RSA public key. A plaintext
DataFrame never crosses the network boundary -- only an EncryptedPayload
does, and only the enclave's private key (generated by, and never leaving,
the Enclave instance) can open it.
"""

import io
import os
from dataclasses import dataclass

import pandas as pd
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

_OAEP_PADDING = padding.OAEP(
    mgf=padding.MGF1(algorithm=hashes.SHA256()),
    algorithm=hashes.SHA256(),
    label=None,
)


@dataclass(frozen=True)
class EncryptedPayload:
    wrapped_key: bytes
    nonce: bytes
    ciphertext: bytes

    def to_bytes(self) -> bytes:
        parts = (self.wrapped_key, self.nonce, self.ciphertext)
        out = bytearray()
        for part in parts:
            out += len(part).to_bytes(4, "big")
            out += part
        return bytes(out)

    @classmethod
    def from_bytes(cls, data: bytes) -> "EncryptedPayload":
        offset = 0
        fields = []
        for _ in range(3):
            length = int.from_bytes(data[offset : offset + 4], "big")
            offset += 4
            fields.append(data[offset : offset + length])
            offset += length
        return cls(*fields)


def seal_for_transport(df: pd.DataFrame, public_key: rsa.RSAPublicKey) -> EncryptedPayload:
    """Encrypt df for transport to the holder of public_key's matching private key."""
    serialized = df.to_json(orient="columns").encode("utf-8")

    aes_key = AESGCM.generate_key(bit_length=256)
    nonce = os.urandom(12)
    ciphertext = AESGCM(aes_key).encrypt(nonce, serialized, None)

    wrapped_key = public_key.encrypt(aes_key, _OAEP_PADDING)

    return EncryptedPayload(wrapped_key=wrapped_key, nonce=nonce, ciphertext=ciphertext)


def open_payload(payload: EncryptedPayload, private_key: rsa.RSAPrivateKey) -> pd.DataFrame:
    """Decrypt payload. Only succeeds with the matching RSA private key."""
    aes_key = private_key.decrypt(payload.wrapped_key, _OAEP_PADDING)
    serialized = AESGCM(aes_key).decrypt(payload.nonce, payload.ciphertext, None)
    return pd.read_json(io.BytesIO(serialized), orient="columns", convert_dates=False)
